version: "3.8"

services:
  # Serviço do Laravel (API PHP com NGINX) image project
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    container_name: server-api
    volumes:
      - ./api:/var/www
    networks:
      - app-network
    depends_on:
      - database

  # nginx
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
        - "8000:80"
    volumes:
        - ./:/var/www
        - ./docker/nginx/:/etc/nginx/conf.d/ # Carrega a configuração do NGINX
    networks:
        - app-network

  # Serviço do Vue.js (Frontend)
  frontend:
    build:
      context: .
      dockerfile: docker/vue/Dockerfile 
    container_name: client-vuejs
    networks:
      - app-network
    ports:
      - "3000:3000"
    command: npm run serve
    depends_on:
      - app

  # Serviço do banco de dados
  database:
    image: postgres:13
    restart: unless-stopped
    container_name: postgres-db
    environment:
            POSTGRES_DATABASE: ${DB_DATABASE:-solucao}
            POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD:-naruto}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-naruto}
            POSTGRES_USER: ${DB_USERNAME:-postgres}
    
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge